version: "3.8"

services:
  sonar-db:
    image: postgres:15-alpine
    container_name: sonar-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    # no host port mapping needed; SonarQube connects over the internal network
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - sonar-net

  sonarqube:
    image: sonarqube:9.9.5-community   # LTS
    container_name: sonarqube
    depends_on:
      - sonar-db
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      # Optional: adjust memory if needed
      # SONAR_ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9000:9000"   # SonarQube UI
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    networks:
      - sonar-net

volumes:
  sonar_db_data:
  sonar_conf:
  sonar_data:
  sonar_extensions:
  sonar_logs:

networks:
  sonar-net:
