services:
  postgres:
    container_name: job_management_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=job_management
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
        - "3000:3000"
    networks:
        - gv-network

  sonar-db:
    image: postgres:15-alpine
    container_name: sonar-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - sonar-net

  sonarqube:
    image: sonarqube:9.9.5-community   # LTS
    container_name: sonarqube
    depends_on:
      - sonar-db
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    networks:
      - sonar-net

volumes:
  sonar_db_data:
  sonar_conf:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  prometheus_data:
  grafana_data:

networks:
  sonar-net:
  gv-network:
    driver: bridge
